import 'styles'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from '~/lib/utils'
import SmoothCursor from '~/components/miscellaneous/cursor'

const inter = Inter({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('antialiased', inter.variable)}>
        <SmoothCursor />
        {children}
      </body>
    </html>
  )
}
